## Deliverable #1

### Dependency
```{r}
library(tidyverse)
library(dplyr)
library(readr)

### Read CSV file
MechaCar_mpg <- read_csv("MechaCar_mpg.csv")

head (MechaCar_mpg)


lm(mpg ~ spoiler_angle + vehicle_length + vehicle_weight + ground_clearance + AWD,data=MechaCar_mpg) #generate multiple linear regression model


summary(lm(mpg ~ spoiler_angle + vehicle_length + vehicle_weight + ground_clearance + AWD,data=MechaCar_mpg)) #generate summary statistics

```


## Deliverable #2
```{r}
library(readr)
Suspension_Coil <- read_csv("Suspension_Coil.csv")

head (Suspension_Coil) 

total_summary <- summarize(Suspension_Coil, mean(PSI), median(PSI), var(PSI), sd(PSI))

lot_summary <- group_by (Suspension_Coil, Manufacturing_Lot)
summarize (lot_summary, Mean =mean(PSI), Median =median(PSI), Variance=var(PSI), SD =sd(PSI))


```

## Deliverable #3
```{r}
t.test(subset(Suspension_Coil,Manufacturing_Lot =="Lot1")$PSI,mu = 1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot =="Lot2")$PSI,mu = 1500)
t.test(subset(Suspension_Coil,Manufacturing_Lot =="Lot3")$PSI,mu = 1500)

t.test((Suspension_Coil$PSI),MU=1500)

```

## Deliverable #4
```{r}


```